databases:
  - name: stocked-shelves-postgresql
    databaseName: stocked_shelves_postgresql
    user: stocked_shelves
    plan: free

services:
  - type: web
    name: stocked_shelves
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stocked-shelves-postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
