databases:
  - name: stocked-shelves-postgresql
    databaseName: stocked_shelves_postgresql
    region: frankfurt
    user: stocked_shelves
    plan: free

services:
  - type: web
    name: stocked-shelves-web
    region: frankfurt
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stocked-shelves-postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: REDIS_URL
        fromService:
          type: redis
          name: stocked-shelves-sidekiq-redis
          property: connectionString
      - key: HOST
        value: stockedshelves.cabaktomas.cz
      - key: PROTOCOL
        value: https
      - key: MAIL_ADDRESS
        value: 'smtp.seznam.cz'
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_AUTHENTICATION
        value: 'login'
      - key: MAILER_SENDER_EMAIL
        sync: false

  - type: redis
    name: stocked-shelves-sidekiq-redis
    plan: free
    region: frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: stocked-shelves-sidekiq-worker
    runtime: ruby
    region: frankfurt
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: DATABASE_URL # used for deserialization of ActiveJob
        fromDatabase:
          name: stocked-shelves-postgresql
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: stocked-shelves-sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
